### ISSUE TITLE
pdf version of all the notebooks

### ISSUE THREAD

**Issue by Burekasim** [PythonFreeCourse/Notebooks#63]
Hi Yam, 

Thanks a lot for the effort you invested in this project, I hear about it from friends (and family) that wants to learn Python, 
Is there a pdf version of all the notebooks? I want to go over the entire content and it will be much easier in pdf format.

**Comment by yammesicka** [comment]
Hi @Burekasim,

Thanks for reaching out! I appreciate your interest in my Python programming course.

While it is certainly possible to print the Jupyter Notebooks, I highly recommend using them as-is and taking advantage of the interactive nature of the notebooks. One of the main benefits of using Jupyter Notebooks as a teaching method is that learners can dynamically play with the code and run it, which helps to reinforce the concepts being taught.

That being said, I understand that some learners may prefer to have a physical copy of the notebooks for reference, especially if they don't have access to the digital version. If you do decide to print the notebooks (you can do it using CTRL+P, or File -> Print), please keep in mind that the printed version may not include all of the interactive features of the digital version, and may not be the most effective way to learn from the course.

Instead of printing the notebooks, I suggest that you use them as intended and interact with the code examples while reading through the notebooks. This will help you to better understand the concepts being taught and to develop your programming skills more effectively.

If you have any other questions or feedback about the course, please don't hesitate to let me know.
